image: docker:28.3

stages:
  - deploy

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - echo "Configuring SSH access..."
    - apt-get update -y && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$OCR_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$OCR_HOST" >> ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - ssh-add -l
  script:
    - echo Deploying...
    # Выполняем на удаленном хосте силами контейнера:
      # Остановили проект
      # Получаем данные git
      # Запускаем проект
      # Миграции laravel
    - ssh ${OCR_USER}@${OCR_HOST} -p 22 "
      cd ${OCR_REMOTE_PATH} &&
      ls -agl &&
      docker compose -f docker-compose.yml down &&
      git checkout main &&
      git pull &&
      docker compose -f docker-compose.yml up -d --build --remove-orphans &&
      docker compose exec -T ocr-app composer install &&
      docker compose exec -T ocr-app composer update &&
      docker compose exec -T ocr-app php artisan migrate --force
      "
